### ISSUE TITLE
Plone5 compatibility

### ISSUE THREAD

**Issue by cekk** [4teamwork/ftw.avatar#14]
Hi, i'd like to try this product on a Plone5 site.
There is a problem with a deprecated dependency with IOFSImage interface of plone.app.linkintegrity here: https://github.com/4teamwork/ftw.avatar/blob/master/ftw/avatar/browser/configure.zcml

Can we keep compatibility with P4 and P5 somehow?

**Comment by jone** [comment]
If `IOFSImage` is deprecated in Plone 5 I assume that the portrait-functionality does not longer base on `IOFSImage`, right?

This would mean that `ftw.avatar` can not work with Plone 5 as it used to with Plone 4 and a new mechanism to hook into the (new) portrait function must be found.

How does the portrait work in Plone 5?

What is the effect you are experiencing? Do you see any tracebacks?

**Comment by tisto** [comment]
I just ran into this. I am not aware that we changed the avatar storage or anything related in Plone 5. There was a significant change in plone.app.linkintegrity though. @jone are you folks interested in making ftw.avatar compatible with Plone 5?

**Comment by jone** [comment]
We have planned to make a Plone 5 effort in 2019 and make the most important `ftw.*` packages Plone 5 ready, but I think `ftw.avatar` will not be in the first batch because we are not using it very widely. 🤔
